WIP: relayer price awareness
althea-net/cosmos-gravity-bridge pull request #282
Opened 2021-07-02 20:54 UTC by ChristianBorst

2021-07-16 12:44 UTC, jkilpatr commented on solidity/package.json
> +    "evm_fork": "npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_ID} --fork-block-number 12782071",
notice the solidity arbitrary logic test is failing, I suggest we change it's script to use solidity_test_fork and keep evm fork for our new test runner test. That way we can use the pinned block that we updated here in that old test and keep it working.

2021-07-16 12:51 UTC, jkilpatr requested changes
Good work! Just needs some changes to correct for clippy, rustfmt and correct the arbitrary logic solidity test.

2021-07-16 12:51 UTC, jkilpatr commented on tests/run-all-tests.sh
> +#bash all-up-test.sh RELAY_MARKET
this should probably have 'RELAY_MARKET API_KEY' to make it clear how it's intended to be called. Or we could add a bash conditional to only run it when the value is set, probably not needed though.

2021-07-19 20:06 UTC, jkilpatr approved these changes

2021-07-19 23:01 UTC, merged

2021-08-05 13:45 UTC, levicook commented on orchestrator/relayer/src/batch_relaying.rs
> +                        oldest_signed_batch
👋 Might want to include cost and reward in this log statement to improve observability on _why_ it didn't relay.